Repository we-sopt-sibi/client, pull requests merged in 2021-11, with the labels that each got.

#6 Feat/common/header
  src/assets/images/index.js
Labels: :bug: bug

#8 :tada: feat: footer setting
  src/components/common/Footer.jsx
Labels: :tada: enhancement

#9 [article] feat/article/articleBody
  src/assets/icons/dot.svg
  src/assets/images/articleContent2.svg
  src/assets/images/articleWriter.svg
  src/assets/images/img_profile_writer_100dp.svg
  src/assets/images/index.js
  src/components/article/ArticleBody.jsx
  src/components/article/ArticleHeader.jsx
Labels: :tada: enhancement

#14 [article] feat/article/ArticleBodyFooter
  src/assets/icons/likeWhite.svg
  src/components/article/ArticleBodyFooter.jsx
Labels: :tada: enhancement

#15 [article] Feat/article/comment
  src/assets/icons/emoji.svg
  src/assets/images/index.js
  src/components/article/ArticleComment.jsx
  src/components/article/CommentWrite.jsx
Labels: :tada: enhancement

#19 Feat/article/article footer
  public/index.html
  src/assets/images/articleFooterBanner.png
  src/components/article/ArticleFooter.jsx
  src/components/article/ArticleListRecommended.jsx
  src/components/article/ArticleRecommended.jsx
  src/components/article/Banner.jsx
  src/components/article/WriterInfo.jsx
  src/components/common/Footer.jsx
  src/components/common/Header.jsx
  src/components/common/drawer/BtnWrapper.jsx
  src/components/common/drawer/Drawer.jsx
  src/components/common/drawer/DrawerBody.jsx
  src/components/common/drawer/DrawerFooter.jsx
  src/components/common/drawer/DrawerMenu.jsx
  src/components/common/drawer/Profile.jsx
  src/components/index.js
  src/pages/Article.jsx
  src/styles/global-style.js
  src/styles/theme.js
Labels: :bug: bug, :tada: enhancement, :question: question

#23 :bug: fix: drawer list width 조정
  src/components/common/drawer/DrawerMenu.jsx
Labels: :bug: bug

#30 :docs: chore: resolve conflict
  src/components/common/Header.jsx
  src/components/common/drawer/DrawerBody.jsx
  src/components/common/drawer/DrawerFooter.jsx
  src/components/common/drawer/Profile.jsx
Labels: :bug: bug

#34 Feat/common/header
  src/assets/icons/comment.svg
  src/assets/icons/logo.svg
  src/assets/icons/logoMini.svg
  src/assets/icons/logoMiniBg.svg
  src/assets/icons/navHamburger.svg
  src/assets/icons/share.svg
  src/components/Router.jsx
  src/components/common/Footer.jsx
  src/components/index.js
  src/pages/Article.jsx
  src/pages/ArticleList.jsx
Labels: :bug: bug

#35 [article] feat/article/mediaquery
  src/components/article/ArticleBody.jsx
  src/components/article/ArticleBodyFooter.jsx
  src/components/article/ArticleComment.jsx
  src/components/article/ArticleHeader.jsx
  src/components/article/CommentWrite.jsx
  src/styles/theme.js
Labels: :memo: documentation
